/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package janelas;

import classes.Employee;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Asus
 */
public class FrmEmployee extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmployee
     */
    public FrmEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        TfEmail = new javax.swing.JTextField();
        BtDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TfAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TfOffice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TfAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TfPhone = new javax.swing.JTextField();
        TfSalary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TfTax = new javax.swing.JTextField();
        TfInss = new javax.swing.JTextField();
        BtCalcular = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailActionPerformed(evt);
            }
        });

        BtDelete.setText("CANCELAR");
        BtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("ENDEREÇO");

        TfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfAddressActionPerformed(evt);
            }
        });

        jLabel6.setText("CARGO");

        TfOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfOfficeActionPerformed(evt);
            }
        });

        jLabel7.setText("IDADE");

        jLabel8.setText("SALÁRIO");

        jLabel1.setText("ID");

        jLabel2.setText("NOME");

        jLabel3.setText("TELEFONE");

        TfSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfSalaryActionPerformed(evt);
            }
        });

        jLabel4.setText("E-MAIL");

        BtSave.setText("CADASTRAR");
        BtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSaveActionPerformed(evt);
            }
        });

        jLabel9.setText("IMPOSTO");

        jLabel10.setText("INSS");

        TfTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTaxActionPerformed(evt);
            }
        });

        TfInss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfInssActionPerformed(evt);
            }
        });

        BtCalcular.setText("CALCULAR");
        BtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfAddress)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TfName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TfOffice)
                        .addGap(80, 80, 80))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(TfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TfInss)
                                .addContainerGap())))
                    .addComponent(BtCalcular)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TfOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TfInss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BtCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtDelete)
                    .addComponent(BtSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailActionPerformed

    private void TfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfAddressActionPerformed

    private void TfOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfOfficeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOfficeActionPerformed

    private void BtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeleteActionPerformed
        TfId.setText("");
        TfName.setText("");
        TfPhone.setText("");
        TfAge.setText("");
        TfEmail.setText("");
        TfAddress.setText("");
        TfOffice.setText("");
        TfSalary.setText("");
    }//GEN-LAST:event_BtDeleteActionPerformed

    private void TfSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfSalaryActionPerformed

    private void BtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSaveActionPerformed
                if(TfId.getText().equals("") || TfName.getText().equals("") || TfPhone.getText().equals("") ||
                TfAge.getText().equals("") || TfEmail.getText().equals("") || TfAddress.getText().equals("") ||
                TfOffice.getText().equals("") || TfOffice.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos."); 
        }else {
            Employee checkEmployee = new Employee();
            checkEmployee.setId(Integer.parseInt(TfId.getText()));
            checkEmployee.setSalary(Float.parseFloat(TfSalary.getText()));
            checkEmployee.setEmail(TfEmail.getText());
            checkEmployee.setName(TfName.getText());
            checkEmployee.setPhone(TfPhone.getText());          
            checkEmployee.setAddress(TfAddress.getText());
            checkEmployee.setImposto(TfTax.getText());
            checkEmployee.setInss(TfInss.getText());
            checkEmployee.fileSave();
            JOptionPane.showMessageDialog(null, "Cadastro realizado. ");
        }
    }//GEN-LAST:event_BtSaveActionPerformed
        
    private void TfTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTaxActionPerformed

    }//GEN-LAST:event_TfTaxActionPerformed

    private void BtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalcularActionPerformed

        // CALCULO IMPOSTO DE RENDA 
        
        float salarioBruto = Float.parseFloat(TfSalary.getText());
        float imposto = 0.0f;
        
        int casasDecimais = 2;
        DecimalFormat df = new DecimalFormat("#." + "0".repeat(casasDecimais));;
        
        
        if (salarioBruto <= 2112) {
            TfTax.setText("ISENTO");
            
        } else if (salarioBruto <= 2826.66) {
            imposto = (salarioBruto - 2112.01f) * 0.075f;
            TfTax.setText("R$" + df.format(imposto));
            
        } else if (salarioBruto <= 3751.06) {
            imposto = (2826.66f - 2112.01f) * 0.075f + (salarioBruto - 2826.66f) * 0.15f;
            TfTax.setText("R$" + df.format(imposto));
              
        } else if (salarioBruto <= 4664.68) {
            imposto = (3751.06f - 2826.66f) * 0.15f + (salarioBruto - 3751.06f)* 0.225f;
            TfTax.setText("R$" + df.format(imposto));
        
        } else {
            imposto = (4664.68f - 3751.06f) * 0.225f + (salarioBruto - 4664.68f) * 0.275f;
            TfTax.setText("R$" + df.format(imposto));
        }
        
        //CALCULANDO INSS
        
       double inss = 0;
       
       if (salarioBruto <= 1320.00) {
            inss = salarioBruto * 0.075;
    
            TfInss.setText("R$" + df.format(inss)); 
    
        } else if (salarioBruto <= 2571.29) {
            inss = (1320.00 * 0.075) + (salarioBruto - 1320.00) * 0.09;
    
            TfInss.setText("R$" + df.format(inss)); 
    
        } else if (salarioBruto <= 3856.94) {
            inss = (1320.00 * 0.075) + (1251.29 * 0.09) + (salarioBruto - 2571.29) * 0.12;
    
            TfInss.setText("R$" + df.format(inss)); 
    
        } else {
            inss = (1320.00 * 0.075) + (1251.29 * 0.09) + (1285.65 * 0.12) + (salarioBruto - 7507.29) * 0.14;
    
            TfInss.setText("R$" + df.format(inss)); 
    
        }
    }//GEN-LAST:event_BtCalcularActionPerformed

    private void TfInssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfInssActionPerformed
         
    }//GEN-LAST:event_TfInssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmployee().setVisible(true);
            }
        });
           
    }   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalcular;
    private javax.swing.JButton BtDelete;
    private javax.swing.JButton BtSave;
    private javax.swing.JTextField TfAddress;
    private javax.swing.JTextField TfAge;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfId;
    private javax.swing.JTextField TfInss;
    private javax.swing.JTextField TfName;
    private javax.swing.JTextField TfOffice;
    private javax.swing.JTextField TfPhone;
    private javax.swing.JTextField TfSalary;
    private javax.swing.JTextField TfTax;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
